core/OTP/urls.py
from django.urls import path
from .views import OTPView,VerifyOTPView


urlpatterns = [
    path('otp/', OTPView.as_view(), name='otp_view'),
    path('verify-otp/', VerifyOTPView.as_view(), name='verify_otp'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import handler400,handler403, handler404, handler500

from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.i18n import set_language

from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap
sitemaps = {
    'static': StaticViewSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('tarjome', include('rosetta.urls')),

    path('', include(('website.urls' , 'website'), namespace= 'website')),
    path('posts/', include(('blog.urls' , 'blog'), namespace= 'blog')),
    path('books/', include(('books.urls' , 'books'), namespace= 'books')),
    path('', include('website.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('accounts/', include('account.urls')),
    path('comment/', include('comment.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/users/', include('OTP.urls')),
    
    path('tinymce/', include('tinymce.urls')),
    path('robots.txt', include('robots.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]
handler400 = 'website.views.handler_400'
handler403 = 'website.views.handler_403'
handler404 = 'website.views.handler_404'
handler500 = 'website.views.handler_500'

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/website/urls.py
from django.urls import path
from .views import IndexView,aboutus,contactus,TermsAndCondition,NewsletterView,resume

namespaces = 'website'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('aboutus/', aboutus, name='about'),
    path('contactus/', contactus, name='contact'),
    path('resume/', resume, name='resume'),  # Add URL pattern for the index view
    path('terms-and-conditions/', TermsAndCondition, name='Terms-and-conditions'),
    path("newsletter/", NewsletterView.as_view(), name="newsletter"),
]

core/templates/partials/footer.html
{% load static %}
{% load i18n %}
{% load cache %}
<!-- CTA Section -->
<section class="cta-area-3 cta-area-4 position-relative pt-4 z-1 pb-0 ms-0">
    <div class="container">
        <div class="row">
        <div class="col-12">
            <div class="section-title section-tag mb-45">
            <h2 class="title-text">{% translate 'برای یک شروع جدید فرصت را از دست ندهید...' %} </h2>
            </div>
        </div>
        </div>
        <div class="row align-items-end">
        <div class="col-md-6 col-lg-8">
            <div class="section-title section-tag">
                <p class="cta-text">{% blocktranslate trimmed %}
                    با ما در ارتباط باشید تا با شما تماس بگیریم. 
                {% endblocktranslate %}<br>
                {% blocktranslate trimmed %} 
                    ببینیم که چطور می‌توانیم با هم همکاری کنیم و به هم کمک کنیم. 
                {% endblocktranslate %}</p>
            </div>
        </div>
        <div class="col-md-6 col-lg-4">
            <div class="cta-btn-wrapper">
            <a href="{% url 'website:contact' %}" class="theme-btn">{% translate 'ارتباط با ما' %} <i class="fas fa-long-arrow-alt-right"></i></a>
            </div>
        </div>
        </div>
        <hr>
        <div class="row align-items-center justify-content-between">
        <div class="col-md-4">
            <div class="cta-info">
            <span>{% translate 'E-MAIL' %}</span>
            <a href="mailto:haniadibazad@gmail.com">haniadibazad@gmail.com</a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="cta-info">
            <span>{% translate 'شماره تماس' %}</span>
            <a href="tel:09122844353">09122844353</a>
            </div>
        </div>
        <div class="col-md-4 text-md-end">
            <div class="footer-img">
                <svg class="dynamic-svg" version="1.0" xmlns="http://www.w3.org/2000/svg" 
                    width="86.2" 
                    height="60" 
                    viewBox="0 0 700.000000 487.000000" 
                    preserveAspectRatio="xMidYMid meet">
                
                    <g transform="translate(0.000000,487.000000) scale(0.1232,-0.1232)" 
                    stroke="none">
                    <path d="M719 4545 c-118 -22 -227 -60 -249 -86 -45 -54 -134 -194 -166 -263 -45 -97 -64 -175 -64 -257 0 -125 38 -187 230 -378 144 -144 483 -431 509 -431 3 0 24 35 45 78 52 101 172 224 266 270 73 36 157 60 243 69 36 4 57 11 57 18 0 22 -95 304 -145 430 -64 164 -157 353 -204 415 -79 105 -161 141 -331 146 -72 2 -144 -2 -191 -11z"/>
                    <path d="M1561 3419 c-171 -17 -284 -72 -366 -181 -22 -28 -63 -102 -92 -164 l-52 -114 51 -47 c28 -27 57 -54 65 -62 8 -7 16 -11 19 -9 2 3 25 56 51 119 70 173 110 222 217 270 39 17 76 22 188 27 93 3 141 9 144 17 3 6 -9 43 -25 81 l-29 69 -44 1 c-23 1 -81 -2 -127 -7z"/>
                    <path d="M1675 3163 c-170 -12 -301 -116 -370 -291 l-29 -74 18 -61 c58 -205 86 -374 94 -582 l7 -159 240 -108 c396 -177 440 -199 628 -316 83 -51 276 -189 306 -219 7 -8 20 -12 28 -9 8 3 17 6 19 6 2 0 4 8 4 18 0 15 -48 86 -252 374 -18 26 -71 101 -118 168 -216 310 -212 304 -255 311 -58 10 -89 49 -82 108 6 57 33 81 92 81 31 0 49 -6 70 -26 25 -23 27 -30 22 -79 l-5 -54 113 -163 c63 -90 144 -207 182 -260 37 -53 118 -169 178 -257 61 -88 115 -160 121 -161 6 0 17 6 23 14 10 12 6 35 -18 113 -94 309 -127 512 -158 990 -9 144 -21 263 -25 263 -16 0 -256 99 -330 135 -40 21 -143 84 -229 141 -166 111 -151 106 -274 97z"/>
                    <path d="M4360 2805 c-332 -74 -501 -230 -516 -475 l-4 -75 18 51 c38 105 120 216 212 285 54 40 178 104 186 96 3 -3 -23 -25 -58 -49 -185 -130 -289 -288 -306 -467 -8 -85 -1 -142 11 -83 11 52 89 120 209 182 197 100 234 141 282 317 32 115 65 182 106 217 l32 26 -34 -1 c-18 0 -80 -11 -138 -24z"/>
                    <path d="M2900 2652 c56 -49 90 -116 130 -255 37 -130 53 -168 96 -232 44 -67 105 -112 260 -191 184 -94 230 -132 279 -224 l24 -45 1 66 c1 259 -151 511 -410 680 -44 29 -79 54 -77 55 1 2 22 -4 46 -12 209 -72 395 -264 482 -496 l19 -53 -4 90 c-10 233 -131 417 -342 519 -130 64 -322 116 -486 133 l-63 6 45 -41z"/>
                    <path d="M4310 2156 c-73 -16 -182 -75 -250 -135 -66 -59 -191 -200 -257 -292 -204 -282 -303 -392 -437 -488 -231 -164 -471 -167 -652 -8 -68 60 -66 35 2 -30 169 -161 389 -181 630 -57 128 66 286 204 409 359 22 28 42 52 46 55 3 3 39 48 80 100 253 319 416 418 596 365 51 -15 153 -94 153 -118 0 -7 -24 -32 -53 -57 -276 -235 -367 -661 -200 -932 97 -157 281 -196 397 -83 127 123 191 381 156 630 -22 152 -76 340 -117 400 -26 39 -17 53 43 65 92 19 231 -9 307 -62 56 -39 127 -101 127 -111 0 -5 -20 -31 -44 -57 -23 -27 -59 -82 -79 -122 -133 -273 -58 -578 143 -578 54 0 91 20 133 72 54 67 77 142 77 251 0 139 -42 272 -121 382 -17 24 -28 48 -24 54 11 19 76 41 119 41 22 0 63 -7 89 -15 60 -18 157 -84 157 -107 0 -10 -10 -41 -21 -70 -17 -40 -22 -76 -23 -148 0 -85 2 -101 27 -147 43 -83 92 -104 141 -60 38 33 53 102 39 181 -11 66 -60 174 -95 213 -44 47 10 99 101 97 94 -2 166 -43 311 -179 157 -148 194 -170 280 -170 77 1 135 27 174 78 50 66 28 172 -46 217 -64 39 -151 15 -178 -49 -12 -29 -11 -35 7 -59 11 -15 28 -29 37 -30 15 -3 15 -1 -3 17 -43 43 -13 91 56 91 70 0 108 -70 73 -135 -32 -59 -138 -77 -220 -37 -25 12 -99 65 -165 117 -151 121 -224 158 -318 163 -64 4 -71 2 -112 -27 -51 -36 -56 -37 -79 -12 -19 21 -82 54 -145 76 -62 21 -158 19 -205 -4 l-38 -20 -60 49 c-75 61 -165 105 -264 130 -85 22 -137 25 -202 10 l-43 -10 -67 69 c-75 77 -140 114 -227 130 -71 13 -94 13 -165 -3z m412 -426 c54 -156 69 -241 75 -436 5 -146 2 -196 -11 -264 -31 -149 -79 -210 -167 -210 -91 0 -162 59 -188 155 -31 113 4 365 80 573 43 120 139 275 166 270 10 -2 27 -35 45 -88z m643 -92 c47 -96 64 -163 71 -278 10 -156 -19 -262 -82 -301 -60 -37 -134 -3 -164 76 -25 66 -8 271 31 387 33 95 82 188 100 188 4 0 24 -33 44 -72z m465 -105 c27 -70 38 -209 21 -242 -20 -36 -62 -25 -85 22 -24 51 -35 236 -16 292 l13 39 22 -27 c13 -14 33 -52 45 -84z"/>
                    </g>
                </svg>
            </div>
        </div>
        </div>
    </div>
</section>
    <!-- CTA Section -->
<footer class="cta-area-4 position-relative" id="colophon" role="contentinfo">
    <div class="site-info" style="text-align: center">
        Copyright&copy;&nbsp;{{ CURRENT_YEAR }}&nbsp;
        <a href="/" target="blank">{{ SITE_NAME }}</a>
        &nbsp;|&nbsp;

        <a href="" title="SiteMap" target="_blank">
            SiteMap
        </a>
        &nbsp;|&nbsp;
        <a href="" title="RSS Feed" target="_blank">
            RSS Feed
        </a>
        &nbsp;|&nbsp;
        <a href="" title="Friendly links" rel="nofollow" target="_blank">
            Friendly links
        </a>


    </div>
    <div class="site-info" style="text-align: center">
        Powered by
        <a href="#" rel="nofollow" target="blank">Django</a>
        &nbsp;|&nbsp;
        <a href="https://deodar.ir" rel="nofollow" target="blank">Deodar</a>

    </div>

</footer><!-- #colophon -->